root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server"
  delay = 500
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test\\.go"]
  include_ext = ["go"]
  kill_delay = "200ms"
  log = "build-errors.log"
  stop_on_error = true

[log]
  time = true

[color]
  build = "yellow"
  main  = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true
